version: "3.8"

services:
  webapp:
    image: indikaeranga/zap-test-app:latest
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
    ports:
      - "8080:3000"
    networks:
      - zap-net

networks:
  zap-net:
    driver: overlay
